### ISSUE TITLE
List of suggested images has missing OS name

### ISSUE THREAD

**Issue by bmstr-ru** [philipheinser/DigitalOcean-Manager#11]
While creating new droplet the list of images shows only OS versions, but names are missing.
If you select some image (e.g. "14.04 x32", which means "ubuntu 14.04 x32", I suppose) and click the Save button, error message appears: "{"id":"unprocessable_entity","message":"You specified an invalid image for Droplet creation"}"

See the screenshots here: https://carousel.dropbox.com/photos/cc/m0pogkcatzSv4UU

**Comment by bmstr-ru** [comment]
Environment: iPhone 5, iOS 8.3, Russian locale

**Comment by philipheinser** [comment]
@bmstr-ru If you like i can invite you to the beta where this bug is closed. Thanks for submitting!

**Comment by bmstr-ru** [comment]
@philipheinser sounds good! My email is dima@bmstr.ru if needed.
